image: python:3.12-slim

stages:
  - lint
  - test

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

lint-app:
  stage: lint
  script:
    - echo "Запуск линтинга"
    - apt-get update && apt-get install -y git
    - poetry run flake8 .
    - poetry run black --check .
    - poetry run isort --check-only .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test-app:
  stage: test
  services:
    - postgres:15
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: postgres
  script:
    - pytest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
