services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - ./prod_postgres_data/:/var/lib/postgresql/data
    networks:
      - my_network


  backend:
    build:
      dockerfile: backend/Dockerfile
    stop_signal: SIGKILL
    env_file:
      - .env
    container_name: twitter_clone
    volumes:
      - ./frontend/static/:/app/frontend/static
    ports:
      - "8000:8000"
    command: ["/app/docker-entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network


  frontend:
    build:
      dockerfile: frontend/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/static/:/app/frontend/static
    depends_on:
      - backend
    restart: always
    networks:
      - my_network



  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - my_network


networks:
  my_network:
    driver: bridge