services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    networks:
      - my_network


  app:
    build:
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    env_file:
      - .env
    container_name: twitter_clone
    volumes:
      - ./static/:/app/static/
    ports:
      - "8000:8000"
    command: ["/app/docker-entrypoint.sh"]
    depends_on:
      - db
    networks:
      - my_network


  nginx_server:
      container_name: nginx
      image: nginx
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - ./static/:/app/static/
      restart: always
      ports:
        - 80:80
      depends_on:
        - app
      networks:
        - my_network


volumes:
    postgres-data:


networks:
  my_network:
    driver: bridge