apiVersion: v1
kind: Secret
metadata:
  name: migration-secret
  labels:
    app: fastapi-migration
data:
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_NAME: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=