apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: my-app
data:
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ== # cG9zdGdyZXMtc3Zj
  POSTGRES_PORT: NTQzMg==
  POSTGRES_NAME: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
