apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nginx.pvName | default "nginx-pv" }}
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce  # Используем ReadWriteOnce для совместимости
  hostPath:
    path: "/data/nginx-pv"
