apiVersion: v1
kind: Secret
metadata:
  name: migration-secret
  labels:
    app: fastapi-migration
data:
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | b64enc | quote }}
  POSTGRES_NAME: {{ .Values.postgres.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}