apiVersion: v1
kind: Service
metadata:
  name: application-service
  labels:
    app: application
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}
  type: ClusterIP